library(ggplot2)
library(data.table)
setwd("/media/aditya/APPS/MS BDA I SEM/Computing For Data Science/R/class 9")
df<-fread('Economist_Assignment_Data.csv',drop = 1)
head(df)
tail(df)
str(df)
summary(df)
pl<-ggplot(df,aes(CPI,HDI,color=Region))+geom_point()
pl<-ggplot(df,aes(CPI,HDI,color=Region))+geom_point(shape='O',size=5)
pd<-ggplot(df,aes(CPI,HDI,color=Region))+geom_point(shape='O',size=5)+geom_smooth(method = 'loess')
pl+geom_smooth(aes(group=1))
pl+geom_smooth(method='lm',formula=y~log(x),se=F,color='red',aes(group=1))
pl2<-pl+geom_smooth(method='lm',formula=y~log(x),se=F,color='red',aes(group=1))
pl2
pl3<-pl2+geom_text(data = df[5:25,1:5],aes(label=Country))
pl4<-pl2+geom_text(aes(label=Country))
pl3+scale_x_continuous('Corruption Perception Index 2011 (10=least corrupt)',limits = c(1,10),breaks = 1:10)
pl5<-pl3+scale_x_continuous('Corruption Perception Index,2011 (10=least corrupt)',limits = c(1,10),breaks = 1:10)
pl5
pl5+scale_y_continuous('Human Development Index, 2011 (1=best)')
pl6<-pl5+scale_y_continuous('Human Development Index, 2011 (1=best)')+ggtitle('Corruption and Human Development')
print(pl6)
